apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgresql-{{ values.name }}
  description: "Request Kratix PostgreSQL - {{ values.name }}"
  tags:
    - kratix
    - postgresql
    - gitops
spec:
  type: resource
  lifecycle: experimental
  owner: user:default/guest
