# templates/postgresql-request/template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: postgresql-request
  title: "Kratix - PostgreSQL (GitOps Request)"
  description: "Cria um Resource Request de PostgreSQL para o Kratix via GitOps (commit no repo kratix-gitops-requests)."
  tags:
    - kratix
    - postgresql
    - gitops
spec:
  owner: group:default/platform
  type: service

  parameters:
    - title: "Dados do request"
      required:
        - teamId
        - dbName
        - env
      properties:
        teamId:
          title: Team ID
          type: string
          default: acid
        dbName:
          title: Database Name
          type: string
          default: postgres
        env:
          title: Environment
          type: string
          enum: [dev, prod]
          default: dev

  steps:
    - id: write
      name: Gerar YAML do Resource Request
      action: roadiehq:utils:write-file
      input:
        path: requests/${{ parameters.teamId }}/postgresql-${{ parameters.dbName }}-${{ parameters.env }}.yaml
        content: |
          apiVersion: marketplace.kratix.io/v1alpha1
          kind: postgresql
          metadata:
            name: ${{ parameters.dbName }}-${{ parameters.env }}
            namespace: default
          spec:
            teamId: ${{ parameters.teamId }}
            dbName: ${{ parameters.dbName }}
            env: ${{ parameters.env }}

    - id: publish
      name: Commit no repo GitOps (kratix-gitops-requests)
      action: publish:github:push
      input:
        repoUrl: github.com?owner=clecioantao&repo=kratix-gitops-requests
        branchName: main
        commitMessage: "Kratix request: postgresql ${{ parameters.dbName }} (${{ parameters.env }})"
        sourcePath: .

  output:
    links:
      - title: "Abrir repo GitOps"
        url: https://github.com/clecioantao/kratix-gitops-requests
