# kratix-gitops-requests/templates/postgresql-request/template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql
  namespace: default
  title: "Kratix: PostgreSQL (GitOps Request)"
  description: "Cria um request de PostgreSQL para o Kratix e commita no repo GitOps."
  tags:
    - kratix
    - postgresql
    - gitops

spec:
  owner: user:default/guest
  type: resource

  parameters:
    - title: Dados do PostgreSQL
      required: [name, teamId, env, dbName, destinationEnvironment]
      properties:
        name:
          title: Nome do resource
          type: string
          description: "Nome do PostgreSQL (ex: pg-sistema-x)"
        teamId:
          title: Team ID
          type: string
          default: acid
        env:
          title: Ambiente
          type: string
          default: dev
          enum: [dev, prod]
        dbName:
          title: Database Name
          type: string
          default: postgres

        destinationEnvironment:
          title: Destination Environment
          type: string
          default: dev
          enum: [dev, prod]
          description: "Seleciona o destino/cluster do Kratix via clusterSelectors.environment"

  steps:
    - id: fetch
      name: "Gerar manifest do request"
      action: fetch:template
      input:
        # ✅ essencial: renderizar APENAS o skeleton
        url: ./skeleton
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          teamId: ${{ parameters.teamId }}
          env: ${{ parameters.env }}
          dbName: ${{ parameters.dbName }}
          destinationEnvironment: ${{ parameters.destinationEnvironment }}

    - id: publish
      name: "Commit no repo GitOps"
      action: publish:github
      input:
        repoUrl: github.com?owner=clecioantao&repo=kratix-gitops-requests
        defaultBranch: main
        sourcePath: ./output
        targetPath: requests/postgresql/${{ parameters.name }}
        commitMessage: "Kratix request: postgresql ${{ parameters.name }}"

  output:
    links:
      - title: "Ver repo GitOps"
        url: ${{ steps.publish.output.remoteUrl }}
