apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql-monorepo
  title: "Kratix: PostgreSQL (Monorepo Requests)"
  description: "Cria um request PostgreSQL do Kratix dentro de um monorepo (platform/requests/...)."
  tags:
    - kratix
    - postgresql
    - gitops
spec:
  owner: user:default/guest
  type: resource

  parameters:
    - title: Dados do Request
      required:
        - name
        - namespace
        - teamId
        - dbName
        - environment
      properties:
        name:
          title: Nome do recurso
          type: string
          description: "Nome do CR do Kratix (ex: clecio-banco-kratix-2)"
          pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        namespace:
          title: Namespace
          type: string
          description: "Namespace onde o CR do Kratix será criado (ex: default)"
          default: default
        teamId:
          title: Team ID
          type: string
          description: "TeamId usado pelo Postgres Operator (ex: acid)"
          default: acid
        dbName:
          title: Nome do DB
          type: string
          description: "Nome do database a ser criado (ex: postgres)"
          default: postgres
        env:
          title: env (campo do CR)
          type: string
          description: "Campo env do seu CR (ex: dev)"
          default: dev
        environment:
          title: clusterSelectors.environment
          type: string
          description: "Vai selecionar o destino/cluster no Kratix (ex: dev)"
          default: dev

    - title: Repositório (Monorepo)
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repositório GitHub
          type: string
          description: "Formato: github.com?owner=<ORG|USER>&repo=<REPO>"
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Gerar arquivos do request
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          teamId: ${{ parameters.teamId }}
          dbName: ${{ parameters.dbName }}
          env: ${{ parameters.env }}
          environment: ${{ parameters.environment }}

    # 1) cria uma pasta temporária fixa com os arquivos renderizados
    # 2) move para platform/requests/postgresql/<name>
    - id: move
      name: Mover para a pasta final (sem {{}} no path)
      action: fs:rename
      input:
        files:
          - from: platform/requests/postgresql/_request
            to: platform/requests/postgresql/${{ parameters.name }}

    - id: publish
      name: Commitar no monorepo (main)
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        # OBS: não use branch/commitMessage aqui, seu Backstage rejeitou (schema do action)
        description: "Request Kratix PostgreSQL: ${{ parameters.name }}"

    - id: register
      name: Registrar no Catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: platform/requests/postgresql/${{ parameters.name }}/catalog-info.yaml

  output:
    links:
      - title: Repositório
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Entidade no Catálogo
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
