apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql-monorepo
  title: "Kratix: PostgreSQL (Monorepo Requests)"
  description: "Cria um request PostgreSQL do Kratix dentro de um monorepo (platform/requests/...)."
  tags:
    - kratix
    - postgresql
    - gitops
spec:
  owner: user:default/guest
  type: resource

  parameters:
    - title: Dados do Request
      required:
        - name
        - namespace
        - teamId
        - dbName
        - environment
      properties:
        name:
          title: Nome do recurso
          type: string
          description: "Nome do CR do Kratix (ex: clecio-banco-kratix-2)"
          pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        namespace:
          title: Namespace
          type: string
          default: default
        teamId:
          title: Team ID
          type: string
          default: acid
        dbName:
          title: Nome do DB
          type: string
          default: postgres
        env:
          title: env (campo do CR)
          type: string
          default: dev
        environment:
          title: clusterSelectors.environment
          type: string
          default: dev

    - title: Monorepo (commit direto)
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repositório GitHub (monorepo existente)
          type: string
          description: "Formato: github.com?owner=<ORG|USER>&repo=<REPO>"
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Gerar arquivos do request
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          teamId: ${{ parameters.teamId }}
          dbName: ${{ parameters.dbName }}
          env: ${{ parameters.env }}
          environment: ${{ parameters.environment }}

    - id: move
      name: Mover para a pasta final
      action: fs:rename
      input:
        files:
          - from: platform/requests/postgresql/_request
            to: platform/requests/postgresql/${{ parameters.name }}

    # ✅ Aqui é o pulo do gato: push dentro do repo EXISTENTE
    - id: push
      name: Commit no monorepo (main)
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: main
        commitMessage: "feat(kratix): request postgresql ${{ parameters.name }}"
        sourcePath: .
        targetPath: .

    - id: register
      name: Registrar no Catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.push.output.repoContentsUrl }}
        catalogInfoPath: platform/requests/postgresql/${{ parameters.name }}/catalog-info.yaml

  output:
    links:
      - title: Monorepo
        url: ${{ steps.push.output.remoteUrl }}
      - title: Entidade no Catálogo
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
