apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql-monorepo
  title: "Kratix: PostgreSQL (Monorepo Requests)"
  description: "Cria um request PostgreSQL do Kratix dentro de um monorepo (platform/requests/...)."
spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: "Dados do Request"
      required: ["name", "namespace", "teamId", "dbName", "env", "environment"]
      properties:
        name:
          title: "Nome do request"
          type: string
          description: "Nome do CR do Kratix (ex: clecio-banco-kratix-2)"
          pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        namespace:
          title: "Namespace"
          type: string
          default: "default"
        teamId:
          title: "Team ID"
          type: string
          default: "acid"
        dbName:
          title: "DB Name"
          type: string
          default: "postgres"
        env:
          title: "Env"
          type: string
          default: "dev"
          enum: ["dev", "stg", "prd"]
        environment:
          title: "clusterSelectors.environment"
          type: string
          default: "dev"
          enum: ["dev", "stg", "prd"]

    - title: "Monorepo (commit direto)"
      required: ["repoUrl"]
      properties:
        repoUrl:
          title: "Repositório GitHub (monorepo existente)"
          type: string
          description: "Escolha o repo onde os requests vivem (ex: kratix-gitops-mono)."
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: "Gerar arquivos do request"
      action: fetch:template
      input:
        # ✅ Na sua versão é url (não template)
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          teamId: ${{ parameters.teamId }}
          dbName: ${{ parameters.dbName }}
          env: ${{ parameters.env }}
          environment: ${{ parameters.environment }}

    - id: move
      name: "Mover para a pasta final (sem {{}} no path)"
      action: fs:rename
      input:
        files:
          - from: platform/requests/postgresql/_request
            to: platform/requests/postgresql/${{ parameters.name }}

    - id: push
      name: "Commitar no monorepo (main)"
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        protectDefaultBranch: false
        # ✅ Na sua action é gitCommitMessage (não commitMessage)
        gitCommitMessage: "feat(kratix): request postgresql ${{ parameters.name }}"
        # ✅ Na sua action é sourcePath (não targetPath)
        sourcePath: .
        # Se você tiver integração do GitHub configurada no Backstage, pode remover token.
        # Se NÃO tiver, precisa passar token (PAT) via secrets/config.
        # token: ${{ secrets.GITHUB_TOKEN }}

  output:
    links:
      - title: "Repositório (monorepo)"
        url: ${{ steps.push.output.remoteUrl }}
      - title: "Conteúdo no GitHub"
        url: ${{ steps.push.output.repoContentsUrl }}
