apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql-monorepo-direct
  title: "Kratix: PostgreSQL (Monorepo Requests - Direct Commit)"
  description: "Cria um request PostgreSQL do Kratix dentro do monorepo e commita direto na main (requer git actions)."
spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Dados do Request
      required:
        - name
        - namespace
        - teamId
        - dbName
        - env
        - environment
      properties:
        name:
          title: Nome do Request
          type: string
          description: "Nome do CR do Kratix (ex: clecio-banco-kratix-2)"
          pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        namespace:
          title: Namespace
          type: string
          default: default
        teamId:
          title: teamId (Zalando Operator)
          type: string
          default: acid
        dbName:
          title: Nome do DB
          type: string
          default: postgres
        env:
          title: env
          type: string
          default: dev
        environment:
          title: clusterSelectors.environment
          type: string
          default: dev

  steps:
    - id: fetch
      name: Gerar arquivos do request
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          teamId: ${{ parameters.teamId }}
          dbName: ${{ parameters.dbName }}
          env: ${{ parameters.env }}
          environment: ${{ parameters.environment }}

    - id: move
      name: Mover para a pasta final (sem {{}} no path)
      action: fs:rename
      input:
        files:
          - from: platform/requests/postgresql/_request
            to: platform/requests/postgresql/${{ parameters.name }}

    # ⚠️ Esses passos exigem que você tenha actions registradas: git:clone / git:commit / git:push (ou equivalentes)
    - id: clone
      name: Clonar monorepo
      action: git:clone
      input:
        repoUrl: https://github.com/clecioantao/kratix-gitops-mono.git
        targetPath: monorepo

    - id: copy
      name: Copiar arquivos para monorepo
      action: fs:copy
      input:
        from: platform/requests/postgresql/${{ parameters.name }}
        to: monorepo/platform/requests/postgresql/${{ parameters.name }}

    - id: commit
      name: Commit no monorepo
      action: git:commit
      input:
        repoPath: monorepo
        message: "feat(kratix): request postgresql ${{ parameters.name }}"

    - id: push
      name: Push na main
      action: git:push
      input:
        repoPath: monorepo
        branch: main

  output:
    links:
      - title: "Abrir monorepo"
        url: https://github.com/clecioantao/kratix-gitops-mono
      - title: "Pasta do request"
        url: https://github.com/clecioantao/kratix-gitops-mono/tree/main/platform/requests/postgresql/${{ parameters.name }}
