apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql
  namespace: default
  title: "Kratix: PostgreSQL (GitOps Request)"
  description: "Cria um request de PostgreSQL para o Kratix e commita no repo GitOps."
  tags:
    - kratix
    - postgresql
    - gitops

spec:
  owner: user:default/guest
  type: resource

  parameters:
    - title: Dados do PostgreSQL
      required: [name, teamId, env, dbName]
      properties:
        name:
          title: Nome do resource
          type: string
          description: "Nome do PostgreSQL (ex: pg-sistema-x)"
        teamId:
          title: Team ID
          type: string
          default: acid
        env:
          title: Ambiente
          type: string
          default: dev
          enum: [dev, prod]
        dbName:
          title: Database Name
          type: string
          default: postgres

  steps:
    - id: fetch
      name: "Gerar manifest do request"
      action: fetch:template
      input:
        # ✅ obrigatório: de onde o scaffolder vai puxar os arquivos do template
        # Use "./" se os arquivos do template estiverem na mesma pasta do template.yaml
        # ou "./content" se você tiver uma pasta content/ ao lado do template.yaml
        url: ./
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          teamId: ${{ parameters.teamId }}
          env: ${{ parameters.env }}
          dbName: ${{ parameters.dbName }}

    - id: publish
      name: "Commit no repo GitOps"
      action: publish:github
      input:
        repoUrl: github.com?owner=clecioantao&repo=kratix-gitops-requests
        defaultBranch: main
        sourcePath: ./output
        targetPath: requests/postgresql/${{ parameters.name }}
        commitMessage: "Kratix request: postgresql ${{ parameters.name }}"

    - id: register
      name: "Registrar entidade no catálogo"
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        # ✅ precisa apontar para ONDE o catalog-info.yaml foi commitado
        catalogInfoPath: "requests/postgresql/${{ parameters.name }}/catalog-info.yaml"

  output:
    links:
      - title: "Ver repo GitOps"
        url: ${{ steps.publish.output.remoteUrl }}
      - title: "Abrir entidade no catálogo"
        icon: catalog
        entityRef: "component:default/${{ parameters.name }}"
