apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql-monorepo
  title: Kratix - PostgreSQL (Monorepo)
  description: "Cria um request PostgreSQL no monorepo GitOps para o Kratix reconciliar"
  tags:
    - kratix
    - gitops
    - postgresql

spec:
  owner: user:default/guest
  type: resource

  parameters:
    - title: "Informações do Banco"
      required:
        - name
        - namespace
        - teamId
        - dbName
        - env
        - environment
      properties:
        name:
          title: "Nome do recurso"
          type: string
          description: "Nome do CR do Kratix (ex: clecio-banco-kratix-2)"
          pattern: "^[a-z0-9]([a-z0-9-]*[a-z0-9])?$"
        namespace:
          title: "Namespace Kubernetes"
          type: string
          description: "Namespace onde o CR do Kratix será criado (ex: default)"
          default: "default"
        teamId:
          title: "Team ID"
          type: string
          description: "teamId esperado pelo Promise (ex: acid)"
          default: "acid"
        dbName:
          title: "Nome do DB"
          type: string
          description: "Nome do database (ex: postgres)"
          default: "postgres"
        env:
          title: "Env (campo do seu CR)"
          type: string
          description: "Campo env do request (ex: dev)"
          default: "dev"
        environment:
          title: "Cluster Selector - environment"
          type: string
          description: "Valor do clusterSelectors.environment usado pelo pipeline (ex: dev)"
          default: "dev"

    - title: "Destino no Monorepo"
      required:
        - repoUrl
      properties:
        repoUrl:
          title: "Monorepo GitHub"
          type: string
          description: "Formato: github.com?owner=ORG&repo=REPO"
          default: "github.com?owner=clecioantao&repo=kratix-gitops-mono"

  steps:
    - id: fetch
      name: "Gerar arquivos do request"
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: "${{ parameters.name }}"
          namespace: "${{ parameters.namespace }}"
          teamId: "${{ parameters.teamId }}"
          dbName: "${{ parameters.dbName }}"
          env: "${{ parameters.env }}"
          environment: "${{ parameters.environment }}"

    - id: pr
      name: "Abrir Pull Request no monorepo (DEV)"
      action: publish:github:pull-request
      input:
        repoUrl: "${{ parameters.repoUrl }}"
        title: "feat(kratix): request postgresql ${{ parameters.name }}"
        description: "Kratix request gerado pelo Backstage para o recurso: ${{ parameters.name }}"
        branchName: "kratix/postgresql-${{ parameters.name }}"

  output:
    links:
      - title: "Pull Request"
        url: "${{ steps.pr.output.remoteUrl }}"
      - title: "Repositório (monorepo)"
        url: "${{ steps.pr.output.repoContentsUrl }}"
