apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql-monorepo
  title: "Kratix: PostgreSQL (Monorepo Requests)"
  description: "Cria um request PostgreSQL do Kratix dentro de um monorepo (platform/requests/...)."
spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Dados do Request
      required:
        - name
        - namespace
        - teamId
        - dbName
        - env
        - environment
      properties:
        name:
          title: Nome do Request
          type: string
          description: Nome do CR do Kratix (ex: teste-1)
          pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        namespace:
          title: Namespace
          type: string
          default: default
        teamId:
          title: teamId (Zalando Operator)
          type: string
          default: acid
        dbName:
          title: Nome do DB
          type: string
          default: postgres
        env:
          title: env
          type: string
          default: dev
        environment:
          title: clusterSelectors.environment
          type: string
          default: dev

    - title: Monorepo (commit direto)
      description: "Em DEV, comitamos direto na main do monorepo."
      required: []
      properties:
        host:
          title: Host
          type: string
          default: github.com
          enum: [github.com]
          ui:disabled: true

        owner:
          title: Owner
          type: string
          default: clecioantao
          ui:widget: hidden

        repo:
          title: Repositório
          type: string
          default: kratix-gitops-mono
          ui:widget: hidden

        # opcional: se você quiser deixar visível, remova ui:widget: hidden
        # e mantenha o default preenchido.

  steps:
    - id: fetch
      name: Gerar arquivos do request
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          teamId: ${{ parameters.teamId }}
          dbName: ${{ parameters.dbName }}
          env: ${{ parameters.env }}
          environment: ${{ parameters.environment }}

    - id: move
      name: Mover para a pasta final (sem {{}} no path)
      action: fs:rename
      input:
        files:
          - from: platform/requests/postgresql/_request
            to: platform/requests/postgresql/${{ parameters.name }}

    - id: push
      name: Commitar no monorepo (main)
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.host }}?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        sourcePath: platform/requests/postgresql/${{ parameters.name }}

  output:
    links:
      - title: "Abrir monorepo"
        url: https://github.com/${{ parameters.owner }}/${{ parameters.repo }}
      - title: "Pasta do request"
        url: https://github.com/${{ parameters.owner }}/${{ parameters.repo }}/tree/main/platform/requests/postgresql/${{ parameters.name }}
