apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: "Kratix request repo: postgresql ${{ values.name }}"
  tags:
    - kratix
    - postgresql
spec:
  type: resource
  lifecycle: experimental
  owner: user:default/guest
